version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.6.3
    restart: unless-stopped
    privileged: true

    networks:
      - proxy

    environment:
      TZ: America/Los_Angeles

    volumes:
      - /home/nelson/containers/home_assist:/config
      - /etc/localtime:/etc/localtime:ro

    # Stable USB device access (Zigbee dongle)
    devices:
      - /dev/serial/by-id:/dev/serial/by-id

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.local.nelsonhickman.com`)"
      - "traefik.http.routers.homeassistant.entrypoints=https"
      - "traefik.http.routers.homeassistant.tls=true"
      - "traefik.http.routers.homeassistant.tls.certresolver=cloudflare"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

networks:
  proxy:
    external: true
