version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:2026.2.0
    container_name: cloudflared
    restart: unless-stopped

    command: tunnel --no-autoupdate run

    networks:
      - proxy

    env_file:
      - /home/nelson/containers/cloudflared/.env

    environment:
      TZ: America/Los_Angeles

networks:
  proxy:
    external: true
