version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    command: tunnel --no-autoupdate run

    networks:
      - proxy

    env_file:
      - .env

    environment:
      TUNNEL_TOKEN: "${TUNNEL_TOKEN}"

networks:
  proxy:
    external: true
