services:
  crashplan-pro:

    command:
      - "/init"

    container_name: "crashplan-pro"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/base/sbin:/opt/base/bin"
      - "ENV=/root/.docker_rc"
      - "USER_ID=1000"
      - "GROUP_ID=1000"
      - "SUP_GROUP_IDS="
      - "UMASK=0022"
      - "LANG=en_US.UTF-8"
      - "TZ=Etc/UTC"
      - "KEEP_APP_RUNNING=0"
      - "APP_NICENESS=0"
      - "INSTALL_PACKAGES="
      - "PACKAGES_MIRROR="
      - "CONTAINER_DEBUG=0"
      - "DISPLAY_WIDTH=1920"
      - "DISPLAY_HEIGHT=1080"
      - "DARK_MODE=1"
      - "SECURE_CONNECTION=0"
      - "SECURE_CONNECTION_VNC_METHOD=SSL"
      - "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60"
      - "WEB_LISTENING_PORT=5800"
      - "VNC_LISTENING_PORT=5900"
      - "VNC_PASSWORD="
      - "ENABLE_CJK_FONT=0"
      - "CRASHPLAN_SRV_MAX_MEM=1024M"
      - "CRASHPLAN_SERVER_ADDRESS=SMB"

    hostname: "crashplan"

    image: "jlesage/crashplan-pro"

    ipc: "private"
    restart: unless-stopped
    
    labels:
      org.label-schema.description: "Docker container for CrashPlan"
      org.label-schema.name: "crashplan-pro"
      org.label-schema.schema-version: "1.0"
      org.label-schema.vcs-url: "https://github.com/jlesage/docker-crashplan-pro"
      org.label-schema.version: "24.01.1"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "02:42:ac:11:00:04"

    network_mode: "bridge"

    ports:
      - "5800:5800/tcp"

    volumes:
      - "/docker/appdata/crashplan-pro:/config"
      - "/mnt/nas:/storage:ro"

    working_dir: "/tmp"

version: "3.6"